FROM jc21/rpmbuild-rocky8:latest

LABEL maintainer="Jamie Curnow <jc@jc21.com>"

USER root

COPY docker/scripts/install-golang.sh /tmp/install-golang.sh
RUN /tmp/install-golang.sh \
	&& rm -f /tmp/install-golang.sh

USER rpmbuilder

ENV PATH="${PATH}:/usr/local/go/bin"
