FROM jc21/rpmbuild-rocky8:latest

LABEL maintainer="Jamie Curnow <jc@jc21.com>"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN curl -sSL "https://get.haskellstack.org/" | sh \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& stack upgrade

USER rpmbuilder
